# Generated by Django 5.2 on 2025-04-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=255)),
                ('pleasant', models.BooleanField()),
                ('periodicity', models.CharField(choices=[('daily', 'Раз в день'), ('every_2_days', 'Раз в 2 дня'), ('every_3_days', 'Раз в 3 дня'), ('weekly', 'Раз в неделю')], default='daily', max_length=30)),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_time', models.DurationField()),
                ('is_public', models.BooleanField(default=False)),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habit', to='habit.habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
